### ISSUE TITLE
wrf_install 0 errrors-> no main/wrf.exe

### ISSUE THREAD

**Issue by avances123** [yyr/wrf_install#10]
only 2 broken symlinks created:
```
./WRFV3/run/wrf.exe -> ../main/wrf.exe
./WRFV3/test/em_real/wrf.exe -> ../../main/wrf.exe
```

happens the same with geogrid.exe , and more.

**Comment by auvipy** [comment]
I also dont get .exe files on main/ and wps .exe files too. followed the way according to readme. ubuntu 14.04

**Comment by yyr** [comment]
> I also dont get .exe files on main/ and wps .exe files too. followed the way according to readme. ubuntu 14.04

I can't see errors from your computer. As I wrote above, I may help you if you show more details.

**Comment by auvipy** [comment]
checking for perl5... no
checking for perl... found /usr/bin/perl (perl)
Will use NETCDF in dir: /home/asif/wrf/gcc
PHDF5 not set in environment. Will configure WRF for use without.


If you REALLY want Grib2 output from WRF, modify the arch/Config_new.pl script.
Right now you are not getting the Jasper lib, from the environment, compiled into WRF.


probably this is the main error for not getting hte executable files generated in WPS/main dir
