### ISSUE TITLE
Failing to download with all downloader dav3.3

### ISSUE THREAD

**Issue by auvipy** [yyr/wrf_install#12]
--2015-02-19 11:47:25--  http://www.mmm.ucar.edu/wrf/src/WRFDAV3.3.TAR.gz
Resolving www.mmm.ucar.edu (www.mmm.ucar.edu)... 128.117.225.207
Connecting to www.mmm.ucar.edu (www.mmm.ucar.edu)|128.117.225.207|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-02-19 11:47:28 ERROR 404: Not Found.

**Comment by auvipy** [comment]
/home/asif/scipy/wrf
Downloading.... WRFDAV3.3
Running: wget -c http://www.mmm.ucar.edu/wrf/src/WRFDAV3.3.TAR.gz -P /home/asif/wrf/src -O WRFDAV3.3.TAR.gz
To moniter log file run: tail -f /home/asif/wrf/src/log.download.WRFDAV3.3
Failed

**Comment by yyr** [comment]
Fixed in 83fe10653396f9d8f4c

But I must alert you that, these scripts are never tested for WRFDA. So you may need to work with script sources.

**Comment by auvipy** [comment]
my main need is WRF WPS but now when building getting error. 

wrf$ ./build_app.sh WRF
Building "WRF" .... 
Entering /home/asif/wrf/src/WRFV3 to build WRF
mv: cannot move 'WRFV3' to '/home/asif/wrf/gcc/WRFV3': No such file or directory
/home/asif/scipy/wrf/build/WRF.sh: line 15: cd: /home/asif/wrf/gcc/WRFV3: No such file or directory
NETCDF=/home/asif/wrf/gcc
WRFIO_NCD_LARGE_FILE_SUPPORT=1
WRF_DA_CORE=0
JASPERLIB=/home/asif/wrf/gcc/lib
JASPERINC=/home/asif/wrf/gcc/include
LD_LIBRARY_PATH=/home/asif/wrf/gcc/lib:
LIBINCLUDE=/home/asif/wrf/gcc/lib:/home/asif/wrf/gcc/include:
/home/asif/scipy/wrf/build/WRF.sh: line 34: ./clean: No such file or directory
/home/asif/scipy/wrf/build/WRF.sh: line 39: ./configure: No such file or directory
 **IMPORTANT**
Moving to building WRF now. You can still change configure script
/home/asif/wrf/src/configure.wrf for any final changes.

 Press ENTER to continue.
Can't open configure.wrf: No such file or directory.
Running: ./compile em_real
To moniter log file run: tail -f /home/asif/wrf/src/log.gcc.compile
Failed

**Comment by auvipy** [comment]
./build_app.sh all
Building "ZLIB" .... 
Entering /home/asif/wrf/src/zlib-1.2.8 to build ZLIB
Running: ./configure --prefix=/home/asif/wrf/gcc
To moniter log file run: tail -f /home/asif/wrf/src/zlib-1.2.8/zlib-1.2.8.gcc.config
Done
rm: cannot remove 'CMakeCache.txt': No such file or directory
Running: cmake -DCMAKE_INSTALL_PREFIX:path=/home/asif/wrf/gcc .
To moniter log file run: tail -f /home/asif/wrf/src/zlib-1.2.8/zlib-1.2.8.gcc.config
Failed

**Comment by yyr** [comment]
>  mv: cannot move 'WRFV3' to '/home/asif/wrf/gcc/WRFV3': No such file or directory

thats the problem. there is no source directory at all.

As README suggests (I think you should first read thoroughly if not all scripts) go one by one and go slow. learn what each step is doing.

start by 
````bash
./build_app.sh zlib 
````
If it is successful  then move to  next component.
````bash
./build_app.sh szip 
````
also each one spits lot of log file. you should go read what's the problem.

Please seperate issues, not everything in one thread.

Closing this one.

**Comment by yyr** [comment]
@auvipy Okay, I have rewrote README now. much better than the earlier one. may be you can read now.

**Comment by auvipy** [comment]
@yyr  thanks a lot!

**Comment by auvipy** [comment]
sorry for disturbing so much just for you


asif@asif:~/wrf_install$ source SOURCEME
=================================================================
compiler=gcc
machine=ubuntu
WRF_BASE=/home/asif/wrf
SCRIPTS_DIR=/home/asif/wrf_install
dep_root=gcc  # where dependencies will be installed
=================================================================

 ** IMPORTANT **
Compiler flags are set. If you like to change any of following values,
please see these files.

    "/home/asif/wrf_install/gcc/compiler.env"
    "/home/asif/wrf_install/ubuntu/gcc.env"   (Change if available/create if necessary)

and source this file again.

-----------------------------------------------------------------
COMP=gcc
CC=gcc
CFLAGS=

CXX=g++
CXXFLAGS=

CPP=cpp
CXXCPP=

FC=gfortran
F77=
F9X=
FFLAGS=
-----------------------------------------------------------------
asif@asif:~/wrf_install$ ./download_app.sh ZLIB
Downloading.... zlib-1.2.8
Running: wget -c http://zlib.net/zlib-1.2.8.tar.gz -P /home/asif/wrf/src -O zlib-1.2.8.tar.gz
To moniter log file run: tail -f /home/asif/wrf/src/log.download.zlib-1.2.8
Done
extraction is done and log is written to "/home/asif/wrf/src/log/zlib-1.2.8.tar.gz.extraction.log"
/home/asif/wrf_install
asif@asif:~/wrf_install$ ./build_app.sh ZLIB
Building "ZLIB" .... 
Entering /home/asif/wrf/src/zlib-1.2.8 to build ZLIB
Running: ./configure --prefix=/home/asif/wrf/gcc
To moniter log file run: tail -f /home/asif/wrf/src/zlib-1.2.8/zlib-1.2.8.gcc.config
Done
rm: cannot remove 'CMakeCache.txt': No such file or directory
Running: cmake -DCMAKE_INSTALL_PREFIX:path=/home/asif/wrf/gcc .
To moniter log file run: tail -f /home/asif/wrf/src/zlib-1.2.8/zlib-1.2.8.gcc.config
Failed
asif@asif:~/wrf_install$

**Comment by yyr** [comment]
> To moniter log file run: tail -f /home/asif/wrf/src/zlib-1.2.8/zlib-1.2.8.gcc.config

You need to check that file and search for any `fatal` errors that occured.

**Comment by auvipy** [comment]
do I need cMake installed?

**Comment by auvipy** [comment]
/home/asif/wrf_install/lib/fun.bash: line 59: cmake: command not found

**Comment by auvipy** [comment]
after sudo  apt-get install cmake

asif@asif:~/wrf_install$ ./build_app.sh ZLIB
Building "ZLIB" .... 
Entering /home/asif/wrf/src/zlib-1.2.8 to build ZLIB
Running: ./configure --prefix=/home/asif/wrf/gcc
To moniter log file run: tail -f /home/asif/wrf/src/zlib-1.2.8/zlib-1.2.8.gcc.config
Done
rm: cannot remove 'CMakeCache.txt': No such file or directory
Running: cmake -DCMAKE_INSTALL_PREFIX:path=/home/asif/wrf/gcc .
To moniter log file run: tail -f /home/asif/wrf/src/zlib-1.2.8/zlib-1.2.8.gcc.config
Done
Running: make clean
To moniter log file run: tail -f /home/asif/wrf/src/zlib-1.2.8/zlib-1.2.8.gcc.clean
Done
Running: make
To moniter log file run: tail -f /home/asif/wrf/src/zlib-1.2.8/zlib-1.2.8.gcc.make
Done
Running: make install
To moniter log file run: tail -f /home/asif/wrf/src/zlib-1.2.8/zlib-1.2.8.gcc.install
Done
Successfully built ZLIB

**Comment by auvipy** [comment]
it would be fine if you mention it on read me that cmake is a must need

**Comment by yyr** [comment]
Hmm. may be, but I expect people to know how to fix basic errors.

Any way `pull requests` are most welcome even for documentation.

**Comment by auvipy** [comment]
ok i will do so. + x windows developmet headers are also needed for bulding ncview. 

configure: error: Could not find Athena widgets library and header (checked w/Xmu.h included as well).  Use your package manager to install the X windows development libraries and headers.

**Comment by yyr** [comment]
That error is self explanatory, it says what you should do.

BTW ncview is not needed to build WRF. its optional. See `build_app.sh` script, I commented it out.

````bash
$ head -n 25 build_app.sh 
#!/usr/bin/env bash

THIS_FILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $THIS_FILE_DIR/lib/fun.bash

# Check for Environmental varables.
sourceme_sourced

# change list.
app_list=(
    ZLIB
    SZIP
    JPEG
    # LIBPNG
    JASPER
    UDUNITS2
    MPICH
    HDF5
    NETCDF4
    # NCVIEW
    WRF
    WPS)

#
function usage()

````

**Comment by auvipy** [comment]
thanks. sudo apt-get install xorg-dev helped me to resolve the building issue :)
