### ISSUE TITLE
Adding .env for netcdf-C, fortran python etc.

### ISSUE THREAD

**Issue by auvipy** [yyr/wrf_install#13]
and netcdf-cxx4

**Comment by yyr** [comment]
I don't understand what you mean. elaborate please.

**Comment by auvipy** [comment]
therer are netcdf-c, netcdf-fortran-4.4.0 netcdf-xxx, i am requesting to add installer shell scripting for them too to automate download and build them

**Comment by yyr** [comment]
Why do you need them? 

IIRC after release of netcdf 4.1.2, it got split different modules. I kept 4.1.2 to keep the installation process simple and as of now it seems to work. 

If you want that specific version netcdf version in this package, I am afraid I don't have time to look into that. If you work on it and offer paches I will definitely consider including here.

**Comment by yyr** [comment]
Now this is implemented.
