### ISSUE TITLE
dependency resolving

### ISSUE THREAD

**Issue by yyr** [yyr/wrf_install#2]

**Comment by auvipy** [comment]
hi how do you consider this one ? >> https://github.com/TakashiUNUMA/wrflib_instsh

**Comment by yyr** [comment]
don't know, never used it.

**Comment by auvipy** [comment]
do the same purpose as yours?

**Comment by yyr** [comment]
> do the same purpose as yours?
Hmm, that should be straight forward from the readme, i.e,Yes. both are written to build WRF. 

PS: This discussion is not related to current issue "Dependency resolving".   Start a new issue for any discussion

**Comment by yyr** [comment]
I guess  attempting this would over complicate things.
