### ISSUE TITLE
ZLIB wget command

### ISSUE THREAD

**Issue by mabelsfatalfable** [yyr/wrf_install#24]
The wget command while running "./download_app.sh ZLIB" not working, update/modification on apps/ZLIB.env is required.

Inside ZLIB.env in line 6 

old one;
URL=http://zlib.net/${APP}.${EXT}
the new one;
URL=http://zlib.net/fossils/${APP}.${EXT}

**Comment by yyr** [comment]
Please consider making a pull request. Thank you
